# Generated by Django 5.1.3 on 2024-11-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denval_Juice', '0002_juice_ml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juice',
            name='description',
        ),
        migrations.AlterField(
            model_name='juice',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='juices/'),
        ),
    ]
