# Generated by Django 5.1.3 on 2024-11-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denval_Juice', '0005_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitModelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blend_varieties', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
